# Type Path                 Mode UID     GID     Age Argument
d /run/runloop              0755 runloop runloop -   -
d /var/lib/runloop          0750 runloop runloop -   -
d /var/lib/runloop/pog      0750 runloop runloop -   -
d /var/lib/runloop/pog/vectors 0750 runloop runloop - -
d /var/log/runloop          0750 runloop runloop -   -
