# Type Path                 Mode UID     GID     Age Argument
d /run/runloop              2775 runloop runloop -   -
d /var/lib/runloop          2775 runloop runloop -   -
d /var/lib/runloop/agents   2775 runloop runloop -   -
d /var/lib/runloop/openings 2775 runloop runloop -   -
d /var/lib/runloop/pog      2775 runloop runloop -   -
d /var/lib/runloop/pog/vectors 2775 runloop runloop - -
d /var/log/runloop          2775 runloop runloop -   -
