[agent]
name = "mailer"
version = "0.1.0"
kind = "wasm32-wasip1"

entry_wasm = { path = "bin/mailer.wasm", blake3 = "fb7c8d7301c23856879443ceaf0e7004a4ac18879b116fe72dc34da664ea67e2" }

[ports]
in = ["intent.send.mail.v1"]
out = ["state.mail.result.v1"]

[caps]
file = "policy.caps"

[schemas.with]
type = "object"
additionalProperties = false

[schemas.with.properties.require_human_confirm]
type = "boolean"

[schemas.with.properties.topic]
type = "string"
minLength = 1
